[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.0"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.0.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/cli"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"
